### ISSUE TITLE
Issue on Find path

### ISSUE THREAD

**Issue by rodrigomanara** [rodrigomanara/opencart-ide#2]
I have got last version 1.1.0 from Composer and install it for clear Opencart release.
var_dump($dir) looks something like that:
"/www/opencart.loc/./upload/system/storage/vendor/../upload/admin/model"
and it's doesn't work:)

**Comment by 123fork** [comment]
By default vendor dir path in Opencart is:  './upload/system/storage/vendor/'
In vendor directory this path can be obtained from 'vendor-dir' conposer.json config.
But if you will change vendor path from './upload/system/storage/vendor/'  to './vendor/' and opencart path from './upload/' to  './' or something else, you will lose simple way to get './config.php' path (with directives DIR_SYSTEM & DIR_STORAGE).

And imho therefore this issue can be solved in 2 ways :
1) static path to ./upload/config.php
2) regexp /(.*?)upload/ from _DIR_

**Comment by rodrigomanara** [comment]
ok, lets check both, perhaps I can use finder so I can check from root until we find the path... I will do few test as well.

**Comment by 123fork** [comment]
What about this? :)
composer config extra.opencart.config './upload/config.php'

**Comment by rodrigomanara** [comment]
ok, did u try ? I can add an extra config file so, we can have an option path

**Comment by 123fork** [comment]
I will try today.

**Comment by rodrigomanara** [comment]
did u try can I close ?
